url: "http://jakewharton.com"

highlighter: rouge
permalink: /:title/
markdown: kramdown

future: true

gems:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  presentations:
    output: true
    permalink: /:title/

exclude: [vendor]
